### ISSUE TITLE
Improve telescope startup process

### ISSUE THREAD

**Issue by alexcottner** [mozilla-services/telescope#1435]
The telescope startup process is very slow and prone to error. After a fresh deploy to prod we will see:

1. Errors from load balancer like no healthy upstream and stream timeout
2. Checks failing due to networking errors. ex: Cannot connect to host [snipped]:443 ssl:default [None]

Let's make this startup process better so that it is able to respond to load balancers immediately and can run the checks asynchronously afterward.

**Comment by alexcottner** [comment]
This was something we noticed a few weeks ago but didn't get to dive into troubleshooting. When we deployed telescope, it seemed to take 3-4 minutes before we could open the UI on the updated containers. 

At first we'd get errors from the load balancer stating "no healthy upstream" then "stream timeout". After that we'd see "Cannot connect to host" for a minute. Then everything worked fine. It seems like something is causing the initialization process to take a long time to load.

**Comment by alexcottner** [comment]
Since the migration out of AWS this problem seems to have gone away. Maybe we had an infra problem over there.

**Comment by alexcottner** [comment]
Ran into the problem again today and we noticed the container load order was inverted. Adjusted and that _seems_ to have resolved our problem.

**Comment by leplatrem** [comment]
According to Dustin, the order of the list of containers does not have any major impact, so  https://github.com/mozilla-it/webservices-infra/pull/3108 was probably the reason it got fixed.

However, since we were allowing 1 replica (because cache is stored in memory), the starting container was dependant on the stopping of the previous. By increasing "surge", https://github.com/mozilla-it/webservices-infra/pull/3109, we allow to have 2 instances during rollouts. This is more likely to have fixed the issue.
